# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ main ]
    paths:
      - src/
      - "pom.xml"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [ main ]
    paths:
      - src/
      - "pom.xml"
      - ".github/workflows/build.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 24
      uses: actions/setup-java@v1
      with:
        java-version: 24
    - name: Build with Maven
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
